import { defineConfig } from "vite-plus";

const bindingSources = ["test/binding.test.ts"] as const,
  nodeOnlySources = ["scripts/**/*.mjs", "test/**/*.test.ts"] as const,
  publicApiSources = ["src/**/*.ts"] as const,
  scriptSources = ["scripts/**/*.mjs"] as const,
  testSources = ["test/**/*.test.ts"] as const,
  vectorSources = ["test/vectors.test.ts"] as const;

export default defineConfig({
  check: {
    fmt: true,
    lint: true,
  },
  fmt: {
    arrowParens: "always",
    bracketSameLine: false,
    bracketSpacing: true,
    embeddedLanguageFormatting: "auto",
    endOfLine: "lf",
    experimentalOperatorPosition: "end",
    htmlWhitespaceSensitivity: "css",
    ignorePatterns: ["dist/**", "odd/**", "pnpm-lock.yaml", "**/*.wasm"],
    insertFinalNewline: true,
    objectWrap: "preserve",
    printWidth: 100,
    proseWrap: "always",
    quoteProps: "as-needed",
    semi: true,
    singleAttributePerLine: false,
    singleQuote: false,
    sortImports: true,
    sortPackageJson: {
      sortScripts: true,
    },
    tabWidth: 2,
    trailingComma: "all",
    useTabs: false,
    vueIndentScriptAndStyle: false,
  },
  lint: {
    categories: {
      correctness: "error",
      nursery: "error",
      pedantic: "error",
      perf: "error",
      restriction: "error",
      style: "error",
      suspicious: "error",
    },
    env: {
      browser: true,
    },
    options: {
      denyWarnings: true,
      maxWarnings: 0,
      reportUnusedDisableDirectives: "error",
      respectEslintDisableDirectives: true,
      typeAware: true,
      typeCheck: true,
    },
    overrides: [
      {
        // These files execute only in Node; keep the environment declaration narrow.
        env: {
          node: true,
        },
        files: [...nodeOnlySources],
        rules: {
          "eslint/no-console": "off",
          "import/no-nodejs-modules": [
            "error",
            {
              allow: [
                "node:child_process",
                "node:crypto",
                "node:fs",
                "node:fs/promises",
                "node:os",
                "node:path",
                "node:url",
              ],
            },
          ],
          "node/no-process-env": "off",
          "node/no-sync": "off",
          "node/no-top-level-await": "off",
        },
      },
      {
        files: [...publicApiSources],
        rules: {
          // The package contract intentionally exposes named public symbols.
          "eslint/init-declarations": "off",
          "eslint/max-lines-per-function": "off",
          "eslint/max-statements": "off",
          "eslint/no-duplicate-imports": "off",
          "eslint/no-useless-assignment": "off",
          "eslint/one-var": "off",
          "eslint/sort-imports": "off",
          "eslint/sort-vars": "off",
          "import/exports-last": "off",
          "import/group-exports": "off",
          "import/no-named-export": "off",
          "import/no-nodejs-modules": ["error", { allow: ["node:fs/promises"] }],
          // These two rules prescribe opposite forms for the same small branch.
          "oxc/no-async-await": "off",
          "typescript/prefer-readonly-parameter-types": "off",
          // `typeof process` is the safe cross-runtime existence check.
          "unicorn/no-typeof-undefined": "off",
          "unicorn/prefer-ternary": "off",
        },
      },
      {
        files: [...scriptSources],
        rules: {
          // The build script is a Node-only executable with protocol constants,
          // Synchronous subprocess capture, and a top-level async entry point.
          "eslint/func-style": "off",
          "eslint/max-statements": "off",
          "eslint/no-magic-numbers": "off",
          "eslint/no-ternary": "off",
          "eslint/no-use-before-define": "off",
          "eslint/one-var": "off",
          "eslint/require-unicode-regexp": "off",
          "eslint/sort-imports": "off",
          "eslint/sort-vars": "off",
          "jsdoc/require-param-description": "off",
          "jsdoc/require-returns-description": "off",
          "nextjs/no-assign-module-variable": "off",
          "node/no-sync": "off",
          "node/no-top-level-await": "off",
          "oxc/no-async-await": "off",
          "oxc/no-optional-chaining": "off",
          "oxc/no-rest-spread-properties": "off",
          "typescript/no-unnecessary-condition": "off",
          "typescript/prefer-readonly-parameter-types": "off",
          "unicorn/import-style": "off",
        },
      },
      {
        files: [...testSources],
        // Tests intentionally use explicit vite-plus/test imports and parent-relative source paths.
        plugins: [
          "eslint",
          "react",
          "unicorn",
          "typescript",
          "oxc",
          "import",
          "jsdoc",
          "vitest",
          "jsx-a11y",
          "nextjs",
          "react-perf",
          "promise",
          "node",
          "vue",
        ],
        rules: {
          "import/no-nodejs-modules": ["error", { allow: ["node:fs", "node:path"] }],
          "import/no-relative-parent-imports": "off",
          "jest/max-expects": ["error", { max: 10 }],
          "jest/no-conditional-expect": "off",
          "jest/no-conditional-in-test": "off",
          "jest/prefer-ending-with-an-expect": "off",
          "jest/prefer-expect-assertions": "off",
          "jest/prefer-strict-equal": "off",
          "jest/require-top-level-describe": "off",
          "jest/valid-expect": ["error", { maxArgs: 2 }],
          "vitest/max-expects": ["error", { max: 10 }],
          "vitest/no-importing-vitest-globals": "off",
          "vitest/valid-expect": ["error", { maxArgs: 2 }],
        },
      },
      {
        files: [...bindingSources],
        rules: {
          // Boundary tests intentionally use async cases, compact numeric
          // Fixtures, and a deliberately tiny trapping guest.
          "eslint/func-style": "off",
          "eslint/id-length": "off",
          "eslint/max-lines-per-function": "off",
          "eslint/max-statements": "off",
          "eslint/no-duplicate-imports": "off",
          "eslint/no-magic-numbers": "off",
          "eslint/no-ternary": "off",
          "eslint/no-undefined": "off",
          "eslint/no-void": "off",
          "eslint/one-var": "off",
          "eslint/sort-imports": "off",
          "eslint/sort-vars": "off",
          "oxc/no-async-await": "off",
          "typescript/no-unsafe-type-assertion": "off",
          "unicorn/consistent-function-scoping": "off",
        },
      },
      {
        files: [...vectorSources],
        rules: {
          // Frozen-vector replay is declarative fixture code: it intentionally
          // Filters records, preserves JSON nulls, and uses data-driven loops.
          "eslint/eqeqeq": "off",
          "eslint/func-style": "off",
          "eslint/max-lines": "off",
          "eslint/max-lines-per-function": "off",
          "eslint/max-statements": "off",
          "eslint/no-continue": "off",
          "eslint/no-magic-numbers": "off",
          "eslint/no-ternary": "off",
          "eslint/no-undefined": "off",
          "eslint/one-var": "off",
          "eslint/sort-imports": "off",
          "eslint/sort-vars": "off",
          "jsdoc/require-param": "off",
          "jsdoc/require-returns": "off",
          "oxc/no-async-await": "off",
          "oxc/no-optional-chaining": "off",
          "typescript/no-unsafe-type-assertion": "off",
          "typescript/non-nullable-type-assertion-style": "off",
          "typescript/prefer-readonly-parameter-types": "off",
          "unicorn/consistent-function-scoping": "off",
          "unicorn/import-style": "off",
          "unicorn/no-array-callback-reference": "off",
          "unicorn/no-array-sort": "off",
          "unicorn/no-null": "off",
          "vitest/no-conditional-expect": "off",
          "vitest/no-conditional-in-test": "off",
        },
      },
      {
        files: ["vite.config.ts"],
        rules: {
          // Vite+ configuration files use the framework's default-export convention.
          "import/no-default-export": "off",
        },
      },
    ],
    plugins: [
      "eslint",
      "react",
      "unicorn",
      "typescript",
      "oxc",
      "import",
      "jsdoc",
      "jest",
      "vitest",
      "jsx-a11y",
      "nextjs",
      "react-perf",
      "promise",
      "node",
      "vue",
    ],
    rules: {
      "typescript/await-thenable": "error",
      "typescript/no-floating-promises": "error",
      "typescript/no-misused-promises": "error",
      "typescript/no-unsafe-argument": "error",
      "typescript/no-unsafe-assignment": "error",
      "typescript/no-unsafe-member-access": "error",
      "typescript/no-unsafe-return": "error",
      "typescript/unbound-method": "error",
      "vitest/no-disabled-tests": "error",
      "vitest/no-focused-tests": "error",
    },
  },
  pack: {
    clean: true,
    deps: {
      // Preserve pre-tsdown 0.23 external subpath resolution.
      neverBundle: [/^node:/u],
      resolveDepSubpath: true,
    },
    dts: {
      sourcemap: true,
    },
    entry: ["src/index.ts"],
    format: ["esm"],
    outDir: "dist",
    platform: "neutral",
    sourcemap: true,
    target: "es2022",
    unbundle: true,
  },
  test: {
    environment: "node",
    include: ["test/**/*.test.ts"],
  },
});
