import { mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
  MAPPING_JSON,
  assertGeneratedTreeIsCurrent,
  findStaleGeneratedFiles,
  generateComponents,
  mappingJson,
  summarize,
} from "../src/generate.js";
import type { ComponentMapping, ImportedComponent } from "../src/plan.js";

const SHELL: ImportedComponent = { export: "default", module: "@/shell" };

function control(name: string): ImportedComponent {
  return { export: "default", module: `@/c/${name}` };
}

function fullMapping(): ComponentMapping {
  return {
    components: {
      boolean: control("boolean"),
      choice: control("choice"),
      date: control("date"),
      datetime: control("datetime"),
      integer: control("integer"),
      number: control("number"),
      text: control("text"),
      textarea: control("textarea"),
      time: control("time"),
    },
    shell: SHELL,
  };
}

let outDir = "";

beforeEach(async () => {
  outDir = await mkdtemp(join(tmpdir(), "colander-generate-"));
});

afterEach(async () => {
  await rm(outDir, { force: true, recursive: true });
});

describe(generateComponents, () => {
  it("leaves the tree alone when the mapping has not changed", async () => {
    await generateComponents({ outDir, ...fullMapping() });
    const second = await generateComponents({ outDir, ...fullMapping() });
    expect(second.written).toEqual([]);
    expect(second.changed).toBe(false);
  });

  it("reports the containers it declined, and generates nothing for them", async () => {
    const result = await generateComponents({ outDir, ...fullMapping() });
    expect(result.rejected.map((entry) => entry.type)).toEqual([
      "group",
      "repeater",
      "component-ref",
    ]);
    const written = await readdir(outDir);
    expect(written).not.toContain("group.tsx");
  });

  it("refuses to run at all when the mapping is unusable", async () => {
    await expect(
      generateComponents({ outDir, ...fullMapping(), shell: undefined as never }),
    ).rejects.toThrow(/the field shell is not usable/);
  });
});

describe("pruning", () => {
  it("removes what an earlier run of this package left behind, without being asked", async () => {
    await generateComponents({ outDir, ...fullMapping() });
    // A module from a version that generated TypeScript, carrying the marker, so
    // The compiler recognises it as its own.
    await writeFile(
      join(outDir, "text.tsx"),
      "// Generated by @ailura/colander-compiler. Do not edit.\n",
      "utf8",
    );
    const result = await generateComponents({ outDir, ...fullMapping() });
    expect(result.removed).toEqual(["text.tsx"]);
    await expect(readdir(outDir)).resolves.toEqual([MAPPING_JSON]);
  });

  it("leaves that file alone when pruning is turned off", async () => {
    await generateComponents({ outDir, ...fullMapping() });
    await writeFile(
      join(outDir, "text.tsx"),
      "// Generated by @ailura/colander-compiler. Do not edit.\n",
      "utf8",
    );
    await generateComponents({ outDir, ...fullMapping(), prune: false });
    await expect(readdir(outDir)).resolves.toContain("text.tsx");
  });

  it("keeps a file the consumer keeps beside the tree", async () => {
    await generateComponents({ outDir, ...fullMapping() });
    await writeFile(join(outDir, "notes.ts"), "export const mine = true;\n", "utf8");
    await generateComponents({ outDir, ...fullMapping() });
    await expect(readdir(outDir)).resolves.toContain("notes.ts");
  });
});

describe("the committed tree drift guard", () => {
  it("passes when the tree on disk is what a run would write", async () => {
    await generateComponents({ outDir, ...fullMapping() });
    await expect(findStaleGeneratedFiles({ outDir, ...fullMapping() })).resolves.toEqual([]);
    await expect(
      assertGeneratedTreeIsCurrent({ outDir, ...fullMapping() }),
    ).resolves.toBeUndefined();
  });

  it("covers the mapping as data too", async () => {
    await generateComponents({ outDir, ...fullMapping() });
    await writeFile(join(outDir, MAPPING_JSON), "{}\n", "utf8");
    await expect(findStaleGeneratedFiles({ outDir, ...fullMapping() })).resolves.toContain(
      MAPPING_JSON,
    );
  });
});

describe("the mapping as data", () => {
  it("names the shell, every type, and what was declined", async () => {
    await generateComponents({ outDir, ...fullMapping() });
    const written = JSON.parse(await readFile(join(outDir, MAPPING_JSON), "utf8")) as {
      version: number;
      shell: { module: string; export: string };
      types: Record<string, { module: string; export: string }>;
      declined: { type: string; reason: string }[];
    };
    expect(written.version).toBe(1);
    expect(written.shell).toEqual(SHELL);
    expect(Object.keys(written.types)).toHaveLength(9);
    expect(written.declined.map((entry) => entry.type)).toEqual([
      "group",
      "repeater",
      "component-ref",
    ]);
  });

  it("records a control written as JSX as the expression it is", () => {
    const json = mappingJson({
      plans: [
        {
          component: { jsx: "<input />" },
          properties: [],
          shell: SHELL,
          type: "text",
          value: "string",
        },
      ],
      rejected: [],
    });
    expect(JSON.parse(json).types.text).toEqual({ export: "jsx", module: "<input />" });
  });
});

describe("the rest of the surface", () => {
  it("says what changed, and what was declined", async () => {
    const result = await generateComponents({ outDir, ...fullMapping() }),
      line = summarize(result);
    expect(line).toContain("changed");
    expect(line).toContain("3 declined");
    const second = await generateComponents({ outDir, ...fullMapping() });
    expect(summarize(second)).toContain("unchanged");
  });
});
