/**
 * Writing the generated tree to disk.
 *
 * The tree is real files, not virtual modules, and that is deliberate: a
 * generated control that `tsc` cannot see is a generated control whose type
 * errors nobody will ever find. It also means the editor resolves the same
 * module the bundler does, and an SSR pass reads the same bytes a development
 * server served.
 */

import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";

import { isImportedComponent, planComponents } from "./plan.js";
import type { ComponentMapping, ComponentPlan, RejectedType } from "./plan.js";

/** What one generation run did. */
export interface GenerateResult {
  /** The directory the tree was written into, as the caller supplied it. */
  readonly outDir: string;
  /** The files written or rewritten, relative to the directory. */
  readonly written: readonly string[];
  /** Files this run removed because the tree no longer produces them. */
  readonly removed: readonly string[];
  /** Types the compiler declined, with the reason. */
  readonly rejected: readonly RejectedType[];
  /** False when nothing on disk changed, which is what HMR keys off. */
  readonly changed: boolean;
}

/**
 * What a caller decides about one generation run.
 *
 * The mapping is spelled out at the top level rather than behind a key, so a
 * caller can hand this function the same object shape a bundler configuration
 * holds, with no wrapper to unpack.
 */
export interface GenerateOptions extends ComponentMapping {
  /** The directory to generate into. Created when missing. */
  readonly outDir: string;
  /**
   * A list of paths the generation depends on, watched in development.
   *
   * The mapping module belongs here, and so does the core's semantics module:
   * a change to either changes the output, and neither is a file this package
   * writes.
   */
  readonly dependencies?: readonly string[];
  /**
   * Delete files this package generated previously that are no longer produced.
   *
   * On by default: the directory is this package's to write, and a module left
   * behind for a type the mapping dropped keeps compiling, which makes a dead
   * file look alive. Only files carrying this package's marker are ever removed,
   * so anything a consumer keeps beside the tree survives. Set it to `false` to
   * leave the directory exactly as it is.
   */
  readonly prune?: boolean;
  /**
   * `"report"` (the default) leaves a partial mapping legal. `"refuse"` fails the
   * run when a materializable type has no component, so a consumer that expects
   * to cover every type hears about it from the build rather than from a log line.
   */
  readonly onUnmapped?: "report" | "refuse";
  /** The TypeScript binary the development check runs, when `tsc` is not on PATH. */
  readonly checkTsc?: string;
  /** The TypeScript project the check compiles the tree under. */
  readonly checkProject?: string;
}

const MARKER = "Generated by @ailura/colander-compiler";

async function readIfPresent(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

/**
 * Generate the component tree for one mapping.
 *
 * A file is only rewritten when its bytes actually change, so a run that
 * produces the same tree leaves modification times alone: nothing downstream of
 * the filesystem — a watcher, an editor, a build cache — is told about a change
 * that did not happen.
 *
 * @param options where to write, what to write, and what to watch
 * @returns what was written, removed, declined, and whether anything changed
 */
export async function generateComponents(options: GenerateOptions): Promise<GenerateResult> {
  const outDir = resolve(options.outDir);
  const { plans, rejected } = planComponents(
    { components: options.components, shell: options.shell },
    options.onUnmapped === undefined ? {} : { onUnmapped: options.onUnmapped },
  );
  // Only the mapping is written. The rest of what a form needs is library code or
  // The consumer's own: the prop types are published, the binding is the
  // Consumer's `defineControl` call, and the dispatcher is `renderColanderField`.
  const files = [{ contents: mappingJson({ plans, rejected }), path: MAPPING_JSON }];

  await mkdir(outDir, { recursive: true });

  const written: string[] = [];
  let changed = false;

  for (const file of files) {
    const target = join(outDir, file.path);
    const current = await readIfPresent(target);
    if (current === file.contents) {
      continue;
    }
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, file.contents, "utf8");
    written.push(file.path);
    changed = true;
  }

  const removed: string[] = [];
  if (options.prune !== false) {
    const expected = new Set(files.map((file) => file.path));
    const entries = await readdir(outDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isFile() || expected.has(entry.name)) {
        continue;
      }
      const target = join(outDir, entry.name);
      const contents = await readIfPresent(target);
      // Only files this package wrote are ever removed. A hand-written module
      // That happens to sit next to the tree is none of the compiler's business.
      if (contents === null || !contents.includes(MARKER)) {
        continue;
      }
      await rm(target);
      removed.push(entry.name);
      changed = true;
    }
  }

  return {
    changed,
    outDir,
    rejected,
    removed,
    written,
  };
}

/**
 * The generated modules a development server must re-check after a change.
 *
 * @param outDir the directory the tree was written into
 * @returns absolute paths of the modules in the tree
 */
export async function generatedModules(outDir: string): Promise<readonly string[]> {
  const absolute = resolve(outDir);
  let entries;
  try {
    entries = await readdir(absolute, { withFileTypes: true });
  } catch {
    return [];
  }
  return entries
    .filter(
      (entry) => entry.isFile() && (entry.name.endsWith(".ts") || entry.name.endsWith(".tsx")),
    )
    .map((entry) => join(absolute, entry.name));
}

/**
 * A short, stable description of one generation run, for a build log.
 *
 * @param result what a run did
 * @returns one line naming the outcome
 */
/**
 * The mapping, as data.
 *
 * The tree is TypeScript, which is what the application imports. A build tool, a
 * test, or another generator is better served by the same thing as JSON, and
 * writing it from the same plan is what keeps the two from disagreeing. It is an
 * artifact, not an input: nothing here is read back by the generated code, and
 * the drift guard covers it like every other file in the tree.
 */
export function mappingJson(result: {
  readonly plans: readonly ComponentPlan[];
  readonly rejected: readonly RejectedType[];
}): string {
  const types: Record<string, { module: string; export: string }> = {};
  for (const plan of result.plans) {
    const source = isImportedComponent(plan.component)
      ? plan.component
      : { export: "jsx", module: plan.component.jsx };
    types[plan.type] = source;
  }
  return `${JSON.stringify(
    {
      declined: result.rejected.map((entry) => ({ reason: entry.reason, type: entry.type })),
      shell: result.plans[0]?.shell ?? null,
      types,
      version: 1,
    },
    null,
    2,
  )}\n`;
}

/**
 * The file name the mapping is written under, inside the generated tree.
 */
export const MAPPING_JSON = "colander.map.json";

/**
 * Compare the tree on disk with what the mapping and the core produce now.
 *
 * The generated tree is a gitignored build artifact, reproduced from the
 * mapping and the core's table, so what is on disk is only worth anything while
 * it is the current output of a run. This is the check that says when it is not.
 *
 * @param options the same options a generation takes
 * @returns the files whose contents on disk differ from what a run would write
 */
export async function findStaleGeneratedFiles(
  options: GenerateOptions,
): Promise<readonly string[]> {
  const { plans } = planComponents(
    { components: options.components, shell: options.shell },
    options.onUnmapped === undefined ? {} : { onUnmapped: options.onUnmapped },
  );
  const { rejected } = planComponents(
    { components: options.components, shell: options.shell },
    options.onUnmapped === undefined ? {} : { onUnmapped: options.onUnmapped },
  );
  const expected = [{ contents: mappingJson({ plans, rejected }), path: MAPPING_JSON }];
  const outDir = resolve(options.outDir);
  const stale: string[] = [];

  for (const file of expected) {
    const current = await readIfPresent(join(outDir, file.path));
    if (current !== file.contents) {
      stale.push(file.path);
    }
  }
  return stale;
}

/**
 * Fail when the tree on disk is not what the mapping and the core produce.
 *
 * Written for a test to call, so that a project does not re-implement a byte
 * comparison to find out whether its committed tree is honest.
 *
 * @param options the same options a generation takes
 * @returns nothing; it throws naming every stale file and how to refresh them
 */
export async function assertGeneratedTreeIsCurrent(options: GenerateOptions): Promise<void> {
  const stale = await findStaleGeneratedFiles(options);
  if (stale.length === 0) {
    return;
  }
  throw new Error(
    `The generated component tree in ${options.outDir} is stale: ${stale.join(", ")}. ` +
      "It is committed, so a checkout reads it before anything is generated, and it no longer " +
      "matches the core's semantic table and the consumer's mapping. Regenerate it and commit the result.",
  );
}

export function summarize(result: GenerateResult): string {
  const parts = [`${result.written.length} written`, `${result.removed.length} removed`];
  if (result.rejected.length > 0) {
    parts.push(`${result.rejected.length} declined`);
  }
  const changed = result.changed ? "changed" : "unchanged";
  return `[colander-compiler] ${changed}: ${parts.join(", ")} in ${relative(process.cwd(), result.outDir) || "."}`;
}
